pipeline {
    environment {
        imageName = "franpitri/spring-boot-test"
        registryCredentials = "docker-hub-credentials"
    }
    
    agent any

    stages {
        stage("Clone repo") {
            steps {
                git(url: "https://github.com/franpitri/spring-boot-test.git", branch: "master")
            }
        }
        
        stage("Build") {
            steps {
                script {
                    def app = docker.build(imageName, "-f Dockerfile.multistage .")
                }
            }
        }
        
        stage("Push image") {
            steps {
                script {
                    docker.withRegistry("", registryCredentials) {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }
    }
}
